name: Nightly releases
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  nightly-build:
    name: Build nightly
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v2
      - name: Build node modules
        run: |
          cd web
          npm ci --prefer-offline --no-audit
          npm run-script build
        shell: bash
      - name: Build electron binary
        env:
          GOFLAGS: -mod=vendor
        run: |
          go run build.go build-electron
      - name: Build electron
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_root: 'web'
          build_script_name: 'build-electron'
      - uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GOOGLE_APP_JSON }}
          path: web/release
          destination: octant-nightlies/electron

  push:
    name: Run goreleaser
    needs: [nightly-build]
    runs-on: ubuntu-latest
    container: goreleaser/goreleaser:v0.128.0-cgo
    steps:
      - uses: actions/checkout@v2
      - name: Run goreleaser
        run: |
          git fetch --tags
          git tag -d nightly || :
          git tag nightly
          echo "$GOOGLE_APPLICATION_JSON" > /tmp/gs.json
          goreleaser -f .goreleaser-nightly.yml --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_JSON: ${{ secrets.GOOGLE_APP_JSON }}
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gs.json
